"""create scans findings inventory heatmap recommendations

Revision ID: b853473cd69b
Revises: 
Create Date: 2026-01-29 17:03:30.008851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b853473cd69b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scans',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('github_url', sa.String(length=500), nullable=False),
    sa.Column('repo_name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('message', sa.String(length=300), nullable=False),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('findings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scan_uuid', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('algorithm', sa.String(length=50), nullable=True),
    sa.Column('context', sa.String(length=50), nullable=True),
    sa.Column('file_path', sa.String(length=1000), nullable=True),
    sa.Column('line_start', sa.Integer(), nullable=True),
    sa.Column('line_end', sa.Integer(), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['scan_uuid'], ['scans.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('heatmap_snapshots',
    sa.Column('scan_uuid', sa.UUID(), nullable=False),
    sa.Column('tree', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['scan_uuid'], ['scans.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('scan_uuid')
    )
    op.create_table('inventory_snapshots',
    sa.Column('scan_uuid', sa.UUID(), nullable=False),
    sa.Column('pqc_readiness_score', sa.Integer(), nullable=False),
    sa.Column('algorithm_ratios', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('inventory_table', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['scan_uuid'], ['scans.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('scan_uuid')
    )
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scan_uuid', sa.UUID(), nullable=False),
    sa.Column('priority_rank', sa.Integer(), nullable=False),
    sa.Column('estimated_effort', sa.String(length=20), nullable=False),
    sa.Column('ai_recommendation', sa.Text(), nullable=False),
    sa.Column('algorithm', sa.String(length=50), nullable=True),
    sa.Column('context', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['scan_uuid'], ['scans.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recommendations')
    op.drop_table('inventory_snapshots')
    op.drop_table('heatmap_snapshots')
    op.drop_table('findings')
    op.drop_table('scans')
    # ### end Alembic commands ###
